/* Generated by re2c 3.1 on Fri Sep 25 11:47:16 2026 */
#line 1 "/home/workdir/artifacts/scanner/re2c/scanner.re"
/*
 * scanner.re - Analizzatore lessicale con re2c
 *
 * Equivalente del file scanner.l per Flex fornito: stesse regole,
 * stessi codici di token, stesso comportamento (stampa il token
 * riconosciuto e lo restituisce; ignora commenti/whitespace; segnala
 * errori lessicali).
 *
 * Differenza fondamentale rispetto a Flex: re2c NON genera un programma
 * completo. Genera solo l'istruzione di match (uno switch/goto ottimizzato)
 * a partire dal blocco speciale re2c inserito piu' sotto in yylex(), che va
 * incorporato in un ciclo di scansione scritto a mano: gestione del buffer,
 * di yytext equivalente (qui 'tok'/'cur'), di fine-file e il main sono
 * tutti a carico nostro.
 *
 * Compilazione:
 *   re2c scanner.re -o scanner.c
 *   gcc -Wall -o scanner scanner.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../tokens.h"
#include "../../arena.h"
#include "../../parser/errorCollector.h"


/* --- "yytext" equivalente: cur punta al carattere corrente, tok
   all'inizio del lessema in corso di riconoscimento ---
   'cur' e 'tok' sono STATIC: interni a questo file. Il resto del
   programma (parser.c) non li vede mai direttamente: puo' solo usare
   le funzioni lexer_open/lexer_next_token/lexer_current_lexeme/
   lexer_current_line dichiarate in lexer.h. Questo evita gli 'extern'
   che attraversavano il confine tra modulo scanner e modulo parser. */
static const unsigned char *cur;
static const unsigned char *tok;
static int lineNumber = 1;
static unsigned char *sourceBuffer = NULL;   /* buffer allocato da lexer_open */

#define TOKLEN   ((int)(cur - tok))
#define TOKTEXT  ((const char *)tok)

/*
 * yylex() - equivalente della funzione generata da Flex.
 * Ogni iterazione del for(;;) riconosce un token; i token da ignorare
 * (whitespace, commenti) fanno "continue" invece di "return".
 */
static int yylex(void) {
    const unsigned char *YYMARKER;   /* richiesto da re2c per il backtracking
                                         tra regole con prefissi comuni, es.
                                         "<" vs "<=" */

    for (;;) {
        tok = cur;

        
#line 61 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
{
	unsigned char yych;
	yych = *cur;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '!': goto yy7;
		case '%': goto yy9;
		case '&': goto yy10;
		case '(': goto yy11;
		case ')': goto yy12;
		case '*': goto yy13;
		case '+': goto yy14;
		case ',': goto yy15;
		case '-': goto yy16;
		case '.': goto yy17;
		case '/': goto yy18;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy20;
		case ';': goto yy22;
		case '<': goto yy23;
		case '=': goto yy25;
		case '>': goto yy27;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case '[': goto yy32;
		case ']': goto yy33;
		case 'e': goto yy34;
		case 'f': goto yy35;
		case 'i': goto yy36;
		case 'r': goto yy37;
		case 'w': goto yy38;
		case '{': goto yy39;
		case '|': goto yy40;
		case '}': goto yy41;
		default: goto yy2;
	}
yy1:
	++cur;
#line 128 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return 0; }
#line 160 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy2:
	++cur;
yy3:
#line 130 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{
                          ec_report("ERRORE LESSICALE (linea %d): carattere non valido '%c'\n",
                                    lineNumber, tok[0]);
                          continue;
                      }
#line 170 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy4:
	yych = *++cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 126 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ continue; }
#line 182 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy6:
	++cur;
#line 125 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ lineNumber++; continue; }
#line 187 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy7:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy42;
		default: goto yy8;
	}
yy8:
#line 104 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_NOT; }
#line 197 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy9:
	++cur;
#line 93 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_MOD; }
#line 202 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy10:
	yych = *++cur;
	switch (yych) {
		case '&': goto yy43;
		default: goto yy3;
	}
yy11:
	++cur;
#line 107 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_LPAREN; }
#line 213 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy12:
	++cur;
#line 108 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_RPAREN; }
#line 218 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy13:
	++cur;
#line 91 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_MUL; }
#line 223 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy14:
	++cur;
#line 89 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_PLUS; }
#line 228 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy15:
	++cur;
#line 113 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_COMMA; }
#line 233 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy16:
	++cur;
#line 90 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_MINUS; }
#line 238 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy17:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy44;
		default: goto yy3;
	}
yy18:
	yych = *(YYMARKER = ++cur);
	switch (yych) {
		case '*': goto yy46;
		case '/': goto yy48;
		default: goto yy19;
	}
yy19:
#line 92 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_DIV; }
#line 264 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy20:
	yych = *++cur;
	switch (yych) {
		case '.': goto yy44;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy20;
		default: goto yy21;
	}
yy21:
#line 87 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_NUM_INT; }
#line 284 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy22:
	++cur;
#line 114 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_SEMICOLON; }
#line 289 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy23:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy50;
		default: goto yy24;
	}
yy24:
#line 99 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_LT; }
#line 299 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy25:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy51;
		default: goto yy26;
	}
yy26:
#line 105 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_ASSIGN; }
#line 309 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy27:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy52;
		default: goto yy28;
	}
yy28:
#line 100 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_GT; }
#line 319 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy29:
	yych = *++cur;
yy30:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy31;
	}
yy31:
#line 84 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_ID; }
#line 392 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy32:
	++cur;
#line 109 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_LBRACK; }
#line 397 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy33:
	++cur;
#line 110 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_RBRACK; }
#line 402 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy34:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy53;
		default: goto yy30;
	}
yy35:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy54;
		case 'o': goto yy55;
		default: goto yy30;
	}
yy36:
	yych = *++cur;
	switch (yych) {
		case 'f': goto yy56;
		case 'n': goto yy58;
		default: goto yy30;
	}
yy37:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy59;
		default: goto yy30;
	}
yy38:
	yych = *++cur;
	switch (yych) {
		case 'h': goto yy60;
		default: goto yy30;
	}
yy39:
	++cur;
#line 111 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_LBRACE; }
#line 439 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy40:
	yych = *++cur;
	switch (yych) {
		case '|': goto yy61;
		default: goto yy3;
	}
yy41:
	++cur;
#line 112 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_DEL_RBRACE; }
#line 450 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy42:
	++cur;
#line 96 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_NE; }
#line 455 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy43:
	++cur;
#line 102 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_AND; }
#line 460 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy44:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy44;
		default: goto yy45;
	}
yy45:
#line 86 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_NUM_FLOAT; }
#line 479 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy46:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy47;
		case '*': goto yy62;
		default: goto yy46;
	}
yy47:
	cur = YYMARKER;
	goto yy19;
yy48:
	yych = *++cur;
	switch (yych) {
		case 0x00:
		case '\n': goto yy49;
		default: goto yy48;
	}
yy49:
#line 116 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ continue; }
#line 500 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy50:
	++cur;
#line 97 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_LE; }
#line 505 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy51:
	++cur;
#line 95 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_EQ; }
#line 510 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy52:
	++cur;
#line 98 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_GE; }
#line 515 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy53:
	yych = *++cur;
	switch (yych) {
		case 's': goto yy63;
		default: goto yy30;
	}
yy54:
	yych = *++cur;
	switch (yych) {
		case 'o': goto yy64;
		default: goto yy30;
	}
yy55:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy65;
		default: goto yy30;
	}
yy56:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy57;
	}
yy57:
#line 78 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_IF; }
#line 605 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy58:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy67;
		default: goto yy30;
	}
yy59:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy69;
		default: goto yy30;
	}
yy60:
	yych = *++cur;
	switch (yych) {
		case 'i': goto yy70;
		default: goto yy30;
	}
yy61:
	++cur;
#line 103 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_OP_OR; }
#line 628 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy62:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy47;
		case '*': goto yy62;
		case '/': goto yy71;
		default: goto yy46;
	}
yy63:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy72;
		default: goto yy30;
	}
yy64:
	yych = *++cur;
	switch (yych) {
		case 'a': goto yy74;
		default: goto yy30;
	}
yy65:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy66;
	}
yy66:
#line 81 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_FOR; }
#line 720 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy67:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy68;
	}
yy68:
#line 76 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_INT; }
#line 792 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy69:
	yych = *++cur;
	switch (yych) {
		case 'u': goto yy75;
		default: goto yy30;
	}
yy70:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy76;
		default: goto yy30;
	}
yy71:
	++cur;
#line 117 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{
                              /* un commento a blocco puo' contenere newline:
                                 aggiorna lineNumber per non perdere il conteggio righe */
                              for (const unsigned char *p = tok; p < cur; p++) {
                                  if (*p == '\n') lineNumber++;
                              }
                              continue;
                          }
#line 816 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy72:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy73;
	}
yy73:
#line 79 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_ELSE; }
#line 888 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy74:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy77;
		default: goto yy30;
	}
yy75:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy79;
		default: goto yy30;
	}
yy76:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy80;
		default: goto yy30;
	}
yy77:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy78;
	}
yy78:
#line 77 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_FLOAT; }
#line 978 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy79:
	yych = *++cur;
	switch (yych) {
		case 'n': goto yy82;
		default: goto yy30;
	}
yy80:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy81;
	}
yy81:
#line 80 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_WHILE; }
#line 1056 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
yy82:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy83;
	}
yy83:
#line 82 "/home/workdir/artifacts/scanner/re2c/scanner.re"
	{ return TOK_KW_RETURN; }
#line 1128 "/home/workdir/artifacts/scanner/re2c/scanner_generated.c"
}
#line 135 "/home/workdir/artifacts/scanner/re2c/scanner.re"

    }
}

/* ==================================================================
 * API PUBBLICA DEL LEXER (lexer.h) - unico punto di contatto con il
 * resto del programma. Nessuno fuori da questo file vede piu'
 * 'cur'/'tok'/'yylex' direttamente: niente extern nel parser.
 * ================================================================== */

#include "../../lexer.h"

/* Arena del lexer: possiede il testo di ogni lessema restituito da
   lexer_current_lexeme(). Nessun limite di lunghezza fisso (a
   differenza del vecchio "char lexemeBuf[LEXEME_MAX]"): tok/cur
   puntano gia' dentro sourceBuffer (l'intero file, caricato una
   volta da lexer_open), quindi la dimensione totale mai occupata
   da questa arena e' comunque limitata dalla dimensione del file
   sorgente stesso - non serve un cap ad hoc separato. */
static Arena *lexerArena = NULL;
static char *currentLexeme = NULL;

void lexer_open(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Impossibile aprire il file %s\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);

    lexerArena = arena_create(0);                     // crea l'arena

    unsigned char *buf = arena_alloc(lexerArena, (size_t)len + 1);
    if (len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len) {
        fprintf(stderr, "Errore di lettura del file %s\n", path);
        fclose(f);
        exit(1);
    }
    buf[len] = '\0';
    fclose(f);

    sourceBuffer = buf;                                /* kept for lexer_close comments / debug */
    cur = buf;                                         // punta all'inizio del sorgente
    lineNumber = 1;
}

void lexer_close(void) {
    arena_destroy(lexerArena);    // libera tutto (sourceBuffer + lessemi)
    lexerArena = NULL;
    currentLexeme = NULL;
    cur = NULL;
}

int lexer_next_token(void) {
    int token = yylex();

    int len = (int)(cur - tok);
    if (len < 0) len = 0;
    currentLexeme = arena_strndup(lexerArena, (const char *)tok, (size_t)len);

    return token;
}

const char *lexer_current_lexeme(void) {
    return currentLexeme;
}

int lexer_current_line(void) {
    return lineNumber;
}
