/* Generated by re2c 3.1 on Wed Jul  8 20:07:13 2026 */
#line 1 "scanner.re"
/*
 * scanner.re - Analizzatore lessicale con re2c
 *
 * Equivalente del file scanner.l per Flex fornito: stesse regole,
 * stessi codici di token, stesso comportamento (stampa il token
 * riconosciuto e lo restituisce; ignora commenti/whitespace; segnala
 * errori lessicali).
 *
 * Differenza fondamentale rispetto a Flex: re2c NON genera un programma
 * completo. Genera solo l'istruzione di match (uno switch/goto ottimizzato)
 * a partire dal blocco speciale re2c inserito piu' sotto in yylex(), che va
 * incorporato in un ciclo di scansione scritto a mano: gestione del buffer,
 * di yytext equivalente (qui 'tok'/'cur'), di fine-file e il main sono
 * tutti a carico nostro.
 *
 * Compilazione:
 *   re2c scanner.re -o scanner.c
 *   gcc -Wall -o scanner scanner.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../tokens.h"


/* --- "yytext" equivalente: cur punta al carattere corrente, tok
   all'inizio del lessema in corso di riconoscimento --- */
/* 'cur' e 'tok' NON sono static: sono variabili globali condivise con
   parser.c. 'cur' e' inizializzata da parser.c prima di chiamare yylex();
   'tok'/'cur' insieme delimitano il lessema dell'ultimo token restituito,
   e parser.c le legge subito dopo ogni chiamata a yylex() per catturare
   il testo del token (vedi advance()/setLexeme() in parser.c). */
const unsigned char *cur;
const unsigned char *tok;
static int lineNumber = 1;

#define TOKLEN   ((int)(cur - tok))
#define TOKTEXT  ((const char *)tok)

/*
 * yylex() - equivalente della funzione generata da Flex.
 * Ogni iterazione del for(;;) riconosce un token; i token da ignorare
 * (whitespace, commenti) fanno "continue" invece di "return".
 */
int yylex(void) {
    const unsigned char *YYMARKER;   /* richiesto da re2c per il backtracking
                                         tra regole con prefissi comuni, es.
                                         "<" vs "<=" */

    for (;;) {
        tok = cur;

        
#line 58 "scanner_generated.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *cur;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '!': goto yy7;
		case '%': goto yy9;
		case '&': goto yy10;
		case '(': goto yy11;
		case ')': goto yy12;
		case '*': goto yy13;
		case '+': goto yy14;
		case ',': goto yy15;
		case '-': goto yy16;
		case '/': goto yy17;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		case ';': goto yy21;
		case '<': goto yy22;
		case '=': goto yy24;
		case '>': goto yy26;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		case '[': goto yy31;
		case ']': goto yy32;
		case 'e': goto yy33;
		case 'f': goto yy34;
		case 'i': goto yy35;
		case 'r': goto yy36;
		case 'w': goto yy37;
		case '{': goto yy38;
		case '|': goto yy39;
		case '}': goto yy40;
		default: goto yy2;
	}
yy1:
	++cur;
#line 124 "scanner.re"
	{ return 0; }
#line 157 "scanner_generated.c"
yy2:
	++cur;
yy3:
#line 126 "scanner.re"
	{
                          fprintf(stderr, "ERRORE LESSICALE (linea %d): carattere non valido '%c'\n",
                                  lineNumber, tok[0]);
                          continue;
                      }
#line 167 "scanner_generated.c"
yy4:
	yych = *++cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 122 "scanner.re"
	{ continue; }
#line 179 "scanner_generated.c"
yy6:
	++cur;
#line 121 "scanner.re"
	{ lineNumber++; continue; }
#line 184 "scanner_generated.c"
yy7:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy41;
		default: goto yy8;
	}
yy8:
#line 100 "scanner.re"
	{ printf("TOKEN: OP_NOT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_NOT; }
#line 194 "scanner_generated.c"
yy9:
	++cur;
#line 89 "scanner.re"
	{ printf("TOKEN: OP_MOD (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_MOD; }
#line 199 "scanner_generated.c"
yy10:
	yych = *++cur;
	switch (yych) {
		case '&': goto yy42;
		default: goto yy3;
	}
yy11:
	++cur;
#line 103 "scanner.re"
	{ printf("TOKEN: DEL_LPAREN (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_LPAREN; }
#line 210 "scanner_generated.c"
yy12:
	++cur;
#line 104 "scanner.re"
	{ printf("TOKEN: DEL_RPAREN (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_RPAREN; }
#line 215 "scanner_generated.c"
yy13:
	++cur;
#line 87 "scanner.re"
	{ printf("TOKEN: OP_MUL (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_MUL; }
#line 220 "scanner_generated.c"
yy14:
	++cur;
#line 85 "scanner.re"
	{ printf("TOKEN: OP_PLUS (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_PLUS; }
#line 225 "scanner_generated.c"
yy15:
	++cur;
#line 109 "scanner.re"
	{ printf("TOKEN: DEL_COMMA (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_COMMA; }
#line 230 "scanner_generated.c"
yy16:
	++cur;
#line 86 "scanner.re"
	{ printf("TOKEN: OP_MINUS (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_MINUS; }
#line 235 "scanner_generated.c"
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++cur);
	switch (yych) {
		case '*': goto yy43;
		case '/': goto yy45;
		default: goto yy18;
	}
yy18:
#line 88 "scanner.re"
	{ printf("TOKEN: OP_DIV (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_DIV; }
#line 247 "scanner_generated.c"
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++cur);
	switch (yych) {
		case '.': goto yy47;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		default: goto yy20;
	}
yy20:
#line 83 "scanner.re"
	{ printf("TOKEN: NUM_INT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_NUM_INT; }
#line 268 "scanner_generated.c"
yy21:
	++cur;
#line 110 "scanner.re"
	{ printf("TOKEN: DEL_SEMICOLON (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_SEMICOLON; }
#line 273 "scanner_generated.c"
yy22:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy48;
		default: goto yy23;
	}
yy23:
#line 95 "scanner.re"
	{ printf("TOKEN: OP_LT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_LT; }
#line 283 "scanner_generated.c"
yy24:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy49;
		default: goto yy25;
	}
yy25:
#line 101 "scanner.re"
	{ printf("TOKEN: OP_ASSIGN (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_ASSIGN; }
#line 293 "scanner_generated.c"
yy26:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy50;
		default: goto yy27;
	}
yy27:
#line 96 "scanner.re"
	{ printf("TOKEN: OP_GT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_GT; }
#line 303 "scanner_generated.c"
yy28:
	yych = *++cur;
yy29:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy30;
	}
yy30:
#line 80 "scanner.re"
	{ printf("TOKEN: ID (%.*s)\n", TOKLEN, TOKTEXT); return TOK_ID; }
#line 376 "scanner_generated.c"
yy31:
	++cur;
#line 105 "scanner.re"
	{ printf("TOKEN: DEL_LBRACK (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_LBRACK; }
#line 381 "scanner_generated.c"
yy32:
	++cur;
#line 106 "scanner.re"
	{ printf("TOKEN: DEL_RBRACK (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_RBRACK; }
#line 386 "scanner_generated.c"
yy33:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy51;
		default: goto yy29;
	}
yy34:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy52;
		case 'o': goto yy53;
		default: goto yy29;
	}
yy35:
	yych = *++cur;
	switch (yych) {
		case 'f': goto yy54;
		case 'n': goto yy56;
		default: goto yy29;
	}
yy36:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy57;
		default: goto yy29;
	}
yy37:
	yych = *++cur;
	switch (yych) {
		case 'h': goto yy58;
		default: goto yy29;
	}
yy38:
	++cur;
#line 107 "scanner.re"
	{ printf("TOKEN: DEL_LBRACE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_LBRACE; }
#line 423 "scanner_generated.c"
yy39:
	yych = *++cur;
	switch (yych) {
		case '|': goto yy59;
		default: goto yy3;
	}
yy40:
	++cur;
#line 108 "scanner.re"
	{ printf("TOKEN: DEL_RBRACE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_DEL_RBRACE; }
#line 434 "scanner_generated.c"
yy41:
	++cur;
#line 92 "scanner.re"
	{ printf("TOKEN: OP_NE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_NE; }
#line 439 "scanner_generated.c"
yy42:
	++cur;
#line 98 "scanner.re"
	{ printf("TOKEN: OP_AND (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_AND; }
#line 444 "scanner_generated.c"
yy43:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy44;
		case '*': goto yy60;
		default: goto yy43;
	}
yy44:
	cur = YYMARKER;
	if (yyaccept == 0) {
		goto yy18;
	} else {
		goto yy20;
	}
yy45:
	yych = *++cur;
	switch (yych) {
		case 0x00:
		case '\n': goto yy46;
		default: goto yy45;
	}
yy46:
#line 112 "scanner.re"
	{ continue; }
#line 469 "scanner_generated.c"
yy47:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy61;
		default: goto yy44;
	}
yy48:
	++cur;
#line 93 "scanner.re"
	{ printf("TOKEN: OP_LE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_LE; }
#line 489 "scanner_generated.c"
yy49:
	++cur;
#line 91 "scanner.re"
	{ printf("TOKEN: OP_EQ (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_EQ; }
#line 494 "scanner_generated.c"
yy50:
	++cur;
#line 94 "scanner.re"
	{ printf("TOKEN: OP_GE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_GE; }
#line 499 "scanner_generated.c"
yy51:
	yych = *++cur;
	switch (yych) {
		case 's': goto yy63;
		default: goto yy29;
	}
yy52:
	yych = *++cur;
	switch (yych) {
		case 'o': goto yy64;
		default: goto yy29;
	}
yy53:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy65;
		default: goto yy29;
	}
yy54:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy55;
	}
yy55:
#line 74 "scanner.re"
	{ printf("TOKEN: KW_IF (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_IF; }
#line 589 "scanner_generated.c"
yy56:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy67;
		default: goto yy29;
	}
yy57:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy69;
		default: goto yy29;
	}
yy58:
	yych = *++cur;
	switch (yych) {
		case 'i': goto yy70;
		default: goto yy29;
	}
yy59:
	++cur;
#line 99 "scanner.re"
	{ printf("TOKEN: OP_OR (%.*s)\n", TOKLEN, TOKTEXT); return TOK_OP_OR; }
#line 612 "scanner_generated.c"
yy60:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy44;
		case '*': goto yy60;
		case '/': goto yy71;
		default: goto yy43;
	}
yy61:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy61;
		default: goto yy62;
	}
yy62:
#line 82 "scanner.re"
	{ printf("TOKEN: NUM_FLOAT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_NUM_FLOAT; }
#line 639 "scanner_generated.c"
yy63:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy72;
		default: goto yy29;
	}
yy64:
	yych = *++cur;
	switch (yych) {
		case 'a': goto yy74;
		default: goto yy29;
	}
yy65:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy66;
	}
yy66:
#line 77 "scanner.re"
	{ printf("TOKEN: KW_FOR (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_FOR; }
#line 723 "scanner_generated.c"
yy67:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy68;
	}
yy68:
#line 72 "scanner.re"
	{ printf("TOKEN: KW_INT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_INT; }
#line 795 "scanner_generated.c"
yy69:
	yych = *++cur;
	switch (yych) {
		case 'u': goto yy75;
		default: goto yy29;
	}
yy70:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy76;
		default: goto yy29;
	}
yy71:
	++cur;
#line 113 "scanner.re"
	{
                              /* un commento a blocco puo' contenere newline:
                                 aggiorna lineNumber per non perdere il conteggio righe */
                              for (const unsigned char *p = tok; p < cur; p++) {
                                  if (*p == '\n') lineNumber++;
                              }
                              continue;
                          }
#line 819 "scanner_generated.c"
yy72:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy73;
	}
yy73:
#line 75 "scanner.re"
	{ printf("TOKEN: KW_ELSE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_ELSE; }
#line 891 "scanner_generated.c"
yy74:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy77;
		default: goto yy29;
	}
yy75:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy79;
		default: goto yy29;
	}
yy76:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy80;
		default: goto yy29;
	}
yy77:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy78;
	}
yy78:
#line 73 "scanner.re"
	{ printf("TOKEN: KW_FLOAT (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_FLOAT; }
#line 981 "scanner_generated.c"
yy79:
	yych = *++cur;
	switch (yych) {
		case 'n': goto yy82;
		default: goto yy29;
	}
yy80:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy81;
	}
yy81:
#line 76 "scanner.re"
	{ printf("TOKEN: KW_WHILE (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_WHILE; }
#line 1059 "scanner_generated.c"
yy82:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy83;
	}
yy83:
#line 78 "scanner.re"
	{ printf("TOKEN: KW_RETURN (%.*s)\n", TOKLEN, TOKTEXT); return TOK_KW_RETURN; }
#line 1131 "scanner_generated.c"
}
#line 131 "scanner.re"

    }
}

/* --- main: legge l'intero file in un buffer null-terminated e scansiona --- */