/* Generated by re2c 3.1 on Thu Aug 13 17:57:09 2026 */
#line 1 "scanner.re"
/*
 * scanner.re - Analizzatore lessicale con re2c
 *
 * Equivalente del file scanner.l per Flex fornito: stesse regole,
 * stessi codici di token, stesso comportamento (stampa il token
 * riconosciuto e lo restituisce; ignora commenti/whitespace; segnala
 * errori lessicali).
 *
 * Differenza fondamentale rispetto a Flex: re2c NON genera un programma
 * completo. Genera solo l'istruzione di match (uno switch/goto ottimizzato)
 * a partire dal blocco speciale re2c inserito piu' sotto in yylex(), che va
 * incorporato in un ciclo di scansione scritto a mano: gestione del buffer,
 * di yytext equivalente (qui 'tok'/'cur'), di fine-file e il main sono
 * tutti a carico nostro.
 *
 * Compilazione:
 *   re2c scanner.re -o scanner.c
 *   gcc -Wall -o scanner scanner.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../tokens.h"
#include "../../arena.h"


static const unsigned char *cur;
static const unsigned char *tok;
static int lineNumber = 1;

#define TOKLEN   ((int)(cur - tok))
#define TOKTEXT  ((const char *)tok)


static int yylex(void) {
    const unsigned char *YYMARKER;

    for (;;) {
        tok = cur;

        
#line 60 "scanner_generated.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *cur;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '!': goto yy7;
		case '%': goto yy9;
		case '&': goto yy10;
		case '(': goto yy11;
		case ')': goto yy12;
		case '*': goto yy13;
		case '+': goto yy14;
		case ',': goto yy15;
		case '-': goto yy16;
		case '/': goto yy17;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		case ';': goto yy21;
		case '<': goto yy22;
		case '=': goto yy24;
		case '>': goto yy26;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		case '[': goto yy31;
		case ']': goto yy32;
		case 'e': goto yy33;
		case 'f': goto yy34;
		case 'i': goto yy35;
		case 'r': goto yy36;
		case 'w': goto yy37;
		case '{': goto yy38;
		case '|': goto yy39;
		case '}': goto yy40;
		default: goto yy2;
	}
yy1:
	++cur;
#line 126 "scanner.re"
	{ return 0; }
#line 159 "scanner_generated.c"
yy2:
	++cur;
yy3:
#line 128 "scanner.re"
	{
                          fprintf(stderr, "ERRORE LESSICALE (linea %d): carattere non valido '%c'\n",
                                  lineNumber, tok[0]);
                          continue;
                      }
#line 169 "scanner_generated.c"
yy4:
	yych = *++cur;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 124 "scanner.re"
	{ continue; }
#line 181 "scanner_generated.c"
yy6:
	++cur;
#line 123 "scanner.re"
	{ lineNumber++; continue; }
#line 186 "scanner_generated.c"
yy7:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy41;
		default: goto yy8;
	}
yy8:
#line 102 "scanner.re"
	{ return TOK_OP_NOT; }
#line 196 "scanner_generated.c"
yy9:
	++cur;
#line 91 "scanner.re"
	{ return TOK_OP_MOD; }
#line 201 "scanner_generated.c"
yy10:
	yych = *++cur;
	switch (yych) {
		case '&': goto yy42;
		default: goto yy3;
	}
yy11:
	++cur;
#line 105 "scanner.re"
	{ return TOK_DEL_LPAREN; }
#line 212 "scanner_generated.c"
yy12:
	++cur;
#line 106 "scanner.re"
	{ return TOK_DEL_RPAREN; }
#line 217 "scanner_generated.c"
yy13:
	++cur;
#line 89 "scanner.re"
	{ return TOK_OP_MUL; }
#line 222 "scanner_generated.c"
yy14:
	++cur;
#line 87 "scanner.re"
	{ return TOK_OP_PLUS; }
#line 227 "scanner_generated.c"
yy15:
	++cur;
#line 111 "scanner.re"
	{ return TOK_DEL_COMMA; }
#line 232 "scanner_generated.c"
yy16:
	++cur;
#line 88 "scanner.re"
	{ return TOK_OP_MINUS; }
#line 237 "scanner_generated.c"
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++cur);
	switch (yych) {
		case '*': goto yy43;
		case '/': goto yy45;
		default: goto yy18;
	}
yy18:
#line 90 "scanner.re"
	{ return TOK_OP_DIV; }
#line 249 "scanner_generated.c"
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++cur);
	switch (yych) {
		case '.': goto yy47;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		default: goto yy20;
	}
yy20:
#line 85 "scanner.re"
	{ return TOK_NUM_INT; }
#line 270 "scanner_generated.c"
yy21:
	++cur;
#line 112 "scanner.re"
	{ return TOK_DEL_SEMICOLON; }
#line 275 "scanner_generated.c"
yy22:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy48;
		default: goto yy23;
	}
yy23:
#line 97 "scanner.re"
	{ return TOK_OP_LT; }
#line 285 "scanner_generated.c"
yy24:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy49;
		default: goto yy25;
	}
yy25:
#line 103 "scanner.re"
	{ return TOK_OP_ASSIGN; }
#line 295 "scanner_generated.c"
yy26:
	yych = *++cur;
	switch (yych) {
		case '=': goto yy50;
		default: goto yy27;
	}
yy27:
#line 98 "scanner.re"
	{ return TOK_OP_GT; }
#line 305 "scanner_generated.c"
yy28:
	yych = *++cur;
yy29:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy30;
	}
yy30:
#line 82 "scanner.re"
	{ return TOK_ID; }
#line 378 "scanner_generated.c"
yy31:
	++cur;
#line 107 "scanner.re"
	{ return TOK_DEL_LBRACK; }
#line 383 "scanner_generated.c"
yy32:
	++cur;
#line 108 "scanner.re"
	{ return TOK_DEL_RBRACK; }
#line 388 "scanner_generated.c"
yy33:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy51;
		default: goto yy29;
	}
yy34:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy52;
		case 'o': goto yy53;
		default: goto yy29;
	}
yy35:
	yych = *++cur;
	switch (yych) {
		case 'f': goto yy54;
		case 'n': goto yy56;
		default: goto yy29;
	}
yy36:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy57;
		default: goto yy29;
	}
yy37:
	yych = *++cur;
	switch (yych) {
		case 'h': goto yy58;
		default: goto yy29;
	}
yy38:
	++cur;
#line 109 "scanner.re"
	{ return TOK_DEL_LBRACE; }
#line 425 "scanner_generated.c"
yy39:
	yych = *++cur;
	switch (yych) {
		case '|': goto yy59;
		default: goto yy3;
	}
yy40:
	++cur;
#line 110 "scanner.re"
	{ return TOK_DEL_RBRACE; }
#line 436 "scanner_generated.c"
yy41:
	++cur;
#line 94 "scanner.re"
	{ return TOK_OP_NE; }
#line 441 "scanner_generated.c"
yy42:
	++cur;
#line 100 "scanner.re"
	{ return TOK_OP_AND; }
#line 446 "scanner_generated.c"
yy43:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy44;
		case '*': goto yy60;
		default: goto yy43;
	}
yy44:
	cur = YYMARKER;
	if (yyaccept == 0) {
		goto yy18;
	} else {
		goto yy20;
	}
yy45:
	yych = *++cur;
	switch (yych) {
		case 0x00:
		case '\n': goto yy46;
		default: goto yy45;
	}
yy46:
#line 114 "scanner.re"
	{ continue; }
#line 471 "scanner_generated.c"
yy47:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy61;
		default: goto yy44;
	}
yy48:
	++cur;
#line 95 "scanner.re"
	{ return TOK_OP_LE; }
#line 491 "scanner_generated.c"
yy49:
	++cur;
#line 93 "scanner.re"
	{ return TOK_OP_EQ; }
#line 496 "scanner_generated.c"
yy50:
	++cur;
#line 96 "scanner.re"
	{ return TOK_OP_GE; }
#line 501 "scanner_generated.c"
yy51:
	yych = *++cur;
	switch (yych) {
		case 's': goto yy63;
		default: goto yy29;
	}
yy52:
	yych = *++cur;
	switch (yych) {
		case 'o': goto yy64;
		default: goto yy29;
	}
yy53:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy65;
		default: goto yy29;
	}
yy54:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy55;
	}
yy55:
#line 76 "scanner.re"
	{ return TOK_KW_IF; }
#line 591 "scanner_generated.c"
yy56:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy67;
		default: goto yy29;
	}
yy57:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy69;
		default: goto yy29;
	}
yy58:
	yych = *++cur;
	switch (yych) {
		case 'i': goto yy70;
		default: goto yy29;
	}
yy59:
	++cur;
#line 101 "scanner.re"
	{ return TOK_OP_OR; }
#line 614 "scanner_generated.c"
yy60:
	yych = *++cur;
	switch (yych) {
		case 0x00: goto yy44;
		case '*': goto yy60;
		case '/': goto yy71;
		default: goto yy43;
	}
yy61:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy61;
		default: goto yy62;
	}
yy62:
#line 84 "scanner.re"
	{ return TOK_NUM_FLOAT; }
#line 641 "scanner_generated.c"
yy63:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy72;
		default: goto yy29;
	}
yy64:
	yych = *++cur;
	switch (yych) {
		case 'a': goto yy74;
		default: goto yy29;
	}
yy65:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy66;
	}
yy66:
#line 79 "scanner.re"
	{ return TOK_KW_FOR; }
#line 725 "scanner_generated.c"
yy67:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy68;
	}
yy68:
#line 74 "scanner.re"
	{ return TOK_KW_INT; }
#line 797 "scanner_generated.c"
yy69:
	yych = *++cur;
	switch (yych) {
		case 'u': goto yy75;
		default: goto yy29;
	}
yy70:
	yych = *++cur;
	switch (yych) {
		case 'l': goto yy76;
		default: goto yy29;
	}
yy71:
	++cur;
#line 115 "scanner.re"
	{

                              for (const unsigned char *p = tok; p < cur; p++) {
                                  if (*p == '\n') lineNumber++;
                              }
                              continue;
                          }
#line 821 "scanner_generated.c"
yy72:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy73;
	}
yy73:
#line 77 "scanner.re"
	{ return TOK_KW_ELSE; }
#line 893 "scanner_generated.c"
yy74:
	yych = *++cur;
	switch (yych) {
		case 't': goto yy77;
		default: goto yy29;
	}
yy75:
	yych = *++cur;
	switch (yych) {
		case 'r': goto yy79;
		default: goto yy29;
	}
yy76:
	yych = *++cur;
	switch (yych) {
		case 'e': goto yy80;
		default: goto yy29;
	}
yy77:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy78;
	}
yy78:
#line 75 "scanner.re"
	{ return TOK_KW_FLOAT; }
#line 983 "scanner_generated.c"
yy79:
	yych = *++cur;
	switch (yych) {
		case 'n': goto yy82;
		default: goto yy29;
	}
yy80:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy81;
	}
yy81:
#line 78 "scanner.re"
	{ return TOK_KW_WHILE; }
#line 1061 "scanner_generated.c"
yy82:
	yych = *++cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy28;
		default: goto yy83;
	}
yy83:
#line 80 "scanner.re"
	{ return TOK_KW_RETURN; }
#line 1133 "scanner_generated.c"
}
#line 133 "scanner.re"

    }
}


#include "../../lexer.h"


static Arena *lexerArena = NULL;
static char *currentLexeme = NULL;

void lexer_open(const char *path) {
    // Open source file in binary read mode
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Impossibile aprire il file %s\n", path);
        exit(1);
    }

    // Measure total file size
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);

    // Create memory arena dedicated to lexer storage
    lexerArena = arena_create(0);                     

    // Allocate continuous buffer in arena and read entire file content
    unsigned char *buf = arena_alloc(lexerArena, len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0'; // Null-terminate file buffer string
    fclose(f);

    // Initialize lexer cursor to start of buffer and set initial line counter
    cur = buf;                                         
    lineNumber = 1;
}

void lexer_close(void) {
    // Destroy entire lexer memory arena at once
    arena_destroy(lexerArena);    
    lexerArena = NULL;
    currentLexeme = NULL;
    cur = NULL;
}

int lexer_next_token(void) {
    // Fetch next token code from scanner engine
    int token = yylex();

    // Compute active lexeme length safely
    int len = (int)(cur - tok);
    if (len < 0) len = 0;

    // Duplicate lexeme substring into lexer arena
    currentLexeme = arena_strndup(lexerArena, (const char *)tok, (size_t)len);

    return token;
}

const char *lexer_current_lexeme(void) {
    // Return cached current lexeme string pointer
    return currentLexeme;
}

int lexer_current_line(void) {
    // Return current source code line number
    return lineNumber;
}